version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "items:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  rabbitmq:
      image: rabbitmq:3-management-alpine
      environment:
          RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
          RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
          RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
      ports:
          - 5672:5672
          - 15672:15672



  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
      
  pgadmin:
    image: dpage/pgadmin4:4.24
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"

